<div class="profile-right-content">
    <div class="web-content-header">
        <h2>SENHENG AFFILIATE PROGRAM FAQ </h2>
    </div>
    <div class="profile-setting-container2">
        <div class="profile-item-card" style="display: flex; justify-content: center; align-items: center; background: rgb(245, 224, 225); width: 100%;  margin: 0px auto; border-radius: 5px; text-align: center; padding: 5px;"><span class="label3" style="color: black; font-weight: bold; display: block; width: 100%;">General</span></div>
        <div class="profile-item-card" style="display: flex; justify-content: start; align-items: center; background: transparent; width: 100%;  margin: 0px auto; border-radius: 10px; text-align: center; padding: 5px;"><span class="label3" style="color: black; text-align: start; display: block; width: 100%; font-size: 14px;">1. How do I sign up to be a Senheng affiliate?</span></div>
        <div class="profile-item-card" style="display: flex; justify-content: start; align-items: center; background: transparent; width: 100%;  margin: 0px auto; border-radius: 10px; text-align: center; padding: 5px;"><span class="label3" style="color: black; text-align: start; display: block; width: 100%; margin-left: 30px; font-size: 14px;">• To sign up, visit the Senheng Affiliate Program landing page, click "Sign Up Now," and fill out the registration form with your details. Once submitted, your application will be reviewed for approval.</span></div>
        <div class="profile-item-card" style="display: flex; justify-content: start; align-items: center; background: transparent; width: 100%;  margin: 0px auto; border-radius: 10px; text-align: center; padding: 5px;"><span class="label3" style="color: black; text-align: start; display: block; width: 100%; font-size: 14px;">2. Is there a fee to join?</span></div>
        <div class="profile-item-card" style="display: flex; justify-content: start; align-items: center; background: transparent; width: 100%;  margin: 0px auto; border-radius: 10px; text-align: center; padding: 5px;"><span class="label3" style="color: black; text-align: start; display: block; width: 100%; margin-left: 30px; font-size: 14px;">• No, joining the Senheng Affiliate Program is completely free, with no upfront costs or hidden fees.</span></div>
        <div class="profile-item-card" style="display: flex; justify-content: start; align-items: center; background: transparent; width: 100%;  margin: 0px auto; border-radius: 10px; text-align: center; padding: 5px;"><span class="label3" style="color: black; text-align: start; display: block; width: 100%; font-size: 14px;">3. How do I track my progress and earnings as an affiliate?</span></div>
        <div class="profile-item-card" style="display: flex; justify-content: start; align-items: center; background: transparent; width: 100%;  margin: 0px auto; border-radius: 10px; text-align: center; padding: 5px;"><span class="label3" style="color: black; text-align: start; display: block; width: 100%; margin-left: 30px; font-size: 14px;">• You can track your clicks, conversions, and earnings through the affiliate dashboard, which provides detailed analytics and performance reports.</span></div>
    </div>
    <div class="profile-item-card" style="display: flex; justify-content: center; align-items: center; background: rgb(245, 224, 225); width: 100%;  margin: 0px auto; border-radius: 5px; text-align: center; padding: 5px;"><span class="label3" style="color: black; font-weight: bold; display: block; width: 100%;">Application</span></div>
    <div class="profile-item-card" style="display: flex; justify-content: start; align-items: center; background: transparent; width: 100%;  margin: 0px auto; border-radius: 10px; text-align: center; padding: 5px;"><span class="label3" style="color: black; text-align: start; display: block; width: 100%; font-size: 14px;">1. How long does it take to get approved as an affiliate?</span></div>
    <div class="profile-item-card" style="display: flex; justify-content: start; align-items: center; background: transparent; width: 100%;  margin: 0px auto; border-radius: 10px; text-align: center; padding: 5px;"><span class="label3" style="color: black; text-align: start; display: block; width: 100%; margin-left: 30px; font-size: 14px;">• Approval typically takes 1-2 business days, depending on the volume of applications. You will receive a confirmation email once your application is reviewed.</span></div>
    <div class="profile-item-card" style="display: flex; justify-content: start; align-items: center; background: transparent; width: 100%;  margin: 0px auto; border-radius: 10px; text-align: center; padding: 5px;"><span class="label3" style="color: black; text-align: start; display: block; width: 100%; font-size: 14px;">2. What happens if my application is not submitted successfully? Can I reapply?</span></div>
    <div class="profile-item-card" style="display: flex; justify-content: start; align-items: center; background: transparent; width: 100%;  margin: 0px auto; border-radius: 10px; text-align: center; padding: 5px;"><span class="label3" style="color: black; text-align: start; display: block; width: 100%; margin-left: 30px; font-size: 14px;">• Yes, please check if the information entered matches the details you provided when registering for the Senheng App. You may reapply afterwards.</span></div>
    <div class="profile-item-card" style="display: flex; justify-content: start; align-items: center; background: transparent; width: 100%;  margin: 0px auto; border-radius: 10px; text-align: center; padding: 5px;"><span class="label3" style="color: black; text-align: start; display: block; width: 100%; font-size: 14px;">3. Do I need to be a PlusOne member to join the affiliate program?</span></div>
    <div class="profile-item-card" style="display: flex; justify-content: start; align-items: center; background: transparent; width: 100%;  margin: 0px auto; border-radius: 10px; text-align: center; padding: 5px;"><span class="label3" style="color: black; text-align: start; display: block; width: 100%; margin-left: 30px; font-size: 14px;">• Yes, and all PlusOne members are eligible to join the program.</span></div>
    <div class="profile-item-card" style="display: flex; justify-content: center; align-items: center; background: rgb(245, 224, 225); width: 100%;  margin: 0px auto; border-radius: 5px; text-align: center; padding: 5px;"><span class="label3" style="color: black; font-weight: bold; display: block; width: 100%;">Tools</span></div>
    <div class="profile-item-card" style="display: flex; justify-content: start; align-items: center; background: transparent; width: 100%;  margin: 0px auto; border-radius: 10px; text-align: center; padding: 5px;"><span class="label3" style="color: black; text-align: start; display: block; width: 100%; font-size: 14px;">1. How do I generate and use referral links?</span></div>
    <div class="profile-item-card" style="display: flex; justify-content: start; align-items: center; background: transparent; width: 100%;  margin: 0px auto; border-radius: 10px; text-align: center; padding: 5px;"><span class="label3" style="color: black; text-align: start; display: block; width: 100%; margin-left: 30px; font-size: 14px;">• To generate a product link, visit the product page and click the share button. A slide-up bar will appear with a copy option. Click it to create your unique affiliate link and share on your social platforms.</span></div>
    <div class="profile-item-card" style="display: flex; justify-content: start; align-items: center; background: transparent; width: 100%;  margin: 0px auto; border-radius: 10px; text-align: center; padding: 5px;"><span class="label3" style="color: black; text-align: start; display: block; width: 100%; font-size: 14px;">2. Can I use the dashboard to monitor my audience's click behavior and traffic sources?</span></div>
    <div class="profile-item-card" style="display: flex; justify-content: start; align-items: center; background: transparent; width: 100%;  margin: 0px auto; border-radius: 10px; text-align: center; padding: 5px;"><span class="label3" style="color: black; text-align: start; display: block; width: 100%; margin-left: 30px; font-size: 14px;">• Yes, the dashboard provides some key insights and analytics, allowing you to monitor clicks and conversions. You can also view your balance summary, and the overall snapshot of your performance.</span></div>
    <div class="profile-item-card" style="display: flex; justify-content: start; align-items: center; background: transparent; width: 100%;  margin: 0px auto; border-radius: 10px; text-align: center; padding: 5px;"><span class="label3" style="color: black; text-align: start; display: block; width: 100%; font-size: 14px;">3. What tools are available to help me promote effectively?</span></div>
    <div class="profile-item-card" style="display: flex; justify-content: start; align-items: center; background: transparent; width: 100%;  margin: 0px auto; border-radius: 10px; text-align: center; padding: 5px;"><span class="label3" style="color: black; text-align: start; display: block; width: 100%; margin-left: 30px; font-size: 14px;">• After signing up as an affiliate, you can access the affiliate links (in the app) to include in your content. Use these links to drive traffic and sales.</span></div>
    <div class="profile-item-card" style="display: flex; justify-content: start; align-items: center; background: transparent; width: 100%;  margin: 0px auto; border-radius: 10px; text-align: center; padding: 5px;"><span class="label3" style="color: black; text-align: start; display: block; width: 100%; font-size: 14px;">4. Are reports available to monitor the performance of my affiliate efforts?</span></div>
    <div class="profile-item-card" style="display: flex; justify-content: start; align-items: center; background: transparent; width: 100%;  margin: 0px auto; border-radius: 10px; text-align: center; padding: 5px;"><span class="label3" style="color: black; text-align: start; display: block; width: 100%; margin-left: 30px; font-size: 14px;">• After a while, you will likely want to know how well your promotional efforts are going. Our affiliate dashboard can generate reports to help you figure out what works best for you.</span></div>
    <div class="profile-item-card" style="display: flex; justify-content: center; align-items: center; background: rgb(245, 224, 225); width: 100%;  margin: 0px auto; border-radius: 5px; text-align: center; padding: 5px;"><span class="label3" style="color: black; font-weight: bold; display: block; width: 100%;">Payment Process</span></div>
    <div class="profile-item-card" style="display: flex; justify-content: start; align-items: center; background: transparent; width: 100%;  margin: 0px auto; border-radius: 10px; text-align: center; padding: 5px;"><span class="label3" style="color: black; text-align: start; display: block; width: 100%; font-size: 14px;">1. When can I get paid?</span></div>
    <div class="profile-item-card" style="display: flex; justify-content: start; align-items: center; background: transparent; width: 100%;  margin: 0px auto; border-radius: 10px; text-align: center; padding: 5px;"><span class="label3" style="color: black; text-align: start; display: block; width: 100%; margin-left: 30px; font-size: 14px;">• Payments are processed once commissions are confirmed (after the return/refund period). Learn more about our Return and Refund Policy <a href="<?php echo site_url('/my-account/affiliate-return-refund/'); ?>" style="color: blue;">here</a>.</span></div>
    <div class="profile-item-card" style="display: flex; justify-content: start; align-items: center; background: transparent; width: 100%;  margin: 0px auto; border-radius: 10px; text-align: center; padding: 5px;"><span class="label3" style="color: black; text-align: start; display: block; width: 100%; font-size: 14px;">2. Is there a minimum cashout amount?</span></div>
    <div class="profile-item-card" style="display: flex; justify-content: start; align-items: center; background: transparent; width: 100%;  margin: 0px auto; border-radius: 10px; text-align: center; padding: 5px;"><span class="label3" style="color: black; text-align: start; display: block; width: 100%; margin-left: 30px; font-size: 14px;">• Yes, affiliates must meet a minimum threshold of RM80 before cashout.</span></div>
    <div class="profile-item-card" style="display: flex; justify-content: start; align-items: center; background: transparent; width: 100%;  margin: 0px auto; border-radius: 10px; text-align: center; padding: 5px;"><span class="label3" style="color: black; text-align: start; display: block; width: 100%; font-size: 14px;">3. What are the payment methods?</span></div>
    <div class="profile-item-card" style="display: flex; justify-content: start; align-items: center; background: transparent; width: 100%;  margin: 0px auto; border-radius: 10px; text-align: center; padding: 5px;"><span class="label3" style="color: black; text-align: start; display: block; width: 100%; margin-left: 30px; font-size: 14px;">• Payments are made via bank transfer.</span></div>
    <div class="profile-item-card" style="display: flex; justify-content: start; align-items: center; background: transparent; width: 100%;  margin: 0px auto; border-radius: 10px; text-align: center; padding: 5px;"><span class="label3" style="color: black; text-align: start; display: block; width: 100%; font-size: 14px;">4. What happens if a referred sale is canceled or refunded?</span></div>
    <div class="profile-item-card" style="display: flex; justify-content: start; align-items: center; background: transparent; width: 100%;  margin: 0px auto; border-radius: 10px; text-align: center; padding: 5px;"><span class="label3" style="color: black; text-align: start; display: block; width: 100%; margin-left: 30px; font-size: 14px;">• If a referred sale is canceled or refunded, the commission for that sale is voided and will not be included in your payout.</span></div>
    <div class="profile-item-card" style="display: flex; justify-content: center; align-items: center; background: rgb(245, 224, 225); width: 100%;  margin: 0px auto; border-radius: 5px; text-align: center; padding: 5px;"><span class="label3" style="color: black; font-weight: bold; display: block; width: 100%;">Payment Process</span></div>
    <div class="profile-item-card" style="display: flex; justify-content: start; align-items: center; background: transparent; width: 100%;  margin: 0px auto; border-radius: 10px; text-align: center; padding: 5px;"><span class="label3" style="color: black; text-align: start; display: block; width: 100%; font-size: 14px;">1. I am a brand representative. How can I join as a merchant?</span></div>
    <div class="profile-item-card" style="display: flex; justify-content: start; align-items: center; background: transparent; width: 100%;  margin: 0px auto; border-radius: 10px; text-align: center; padding: 5px;"><span class="label3" style="color: black; text-align: start; display: block; width: 100%; margin-left: 30px; font-size: 14px;">• Get in touch with us at <a href="mailto:affiliate@seco.com.my" style="color: blue;">affiliate@seco.com.my</a>.</span></div>
    <div class="profile-item-card" style="display: flex; justify-content: start; align-items: center; background: transparent; width: 100%;  margin: 0px auto; border-radius: 10px; text-align: center; padding: 5px;"><span class="label3" style="color: black; text-align: start; display: block; width: 100%; font-size: 14px;">2. How can I contact support if I encounter issues with my account or links?</span></div>
    <div class="profile-item-card" style="display: flex; justify-content: start; align-items: center; background: transparent; width: 100%;  margin: 0px auto; border-radius: 10px; text-align: center; padding: 5px;"><span class="label3" style="color: black; text-align: start; display: block; width: 100%; margin-left: 30px; font-size: 14px;">• For any issues related to your account or affiliate links, you can reach out to the support team via email at <a href="mailto:affiliate@seco.com.my" style="color: blue;">affiliate@seco.com.my</a>.</span></div>
    <div class="profile-item-card" style="display: flex; justify-content: start; align-items: center; background: transparent; width: 100%;  margin: 0px auto; border-radius: 10px; text-align: center; padding: 5px;"><span class="label3" style="color: black; text-align: start; display: block; width: 100%; font-size: 14px;">3. What happens if I violate the affiliate program's<a href="<?php echo site_url('/my-account/affiliate-terms-conditions/'); ?>" style="color: blue;"> terms and conditions </a>.?</span></div>
    <div class="profile-item-card" style="display: flex; justify-content: start; align-items: center; background: transparent; width: 100%;  margin: 0px auto; border-radius: 10px; text-align: center; padding: 5px;"><span class="label3" style="color: black; text-align: start; display: block; width: 100%; margin-left: 30px; font-size: 14px;">• Violations of the terms and conditions may result in account suspension or termination, and any unpaid commissions may be forfeited. Ensure compliance by adhering to the program's guidelines.</span></div>
</div>