<table cellpadding="0" cellspacing="0" border="0" bgcolor="" align="center" role="presentation"
       class="bwfbe-block-section-container bwfbe-block-section bwfbe-block-4bf2f08"
       style="border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-spacing: 0px; width: 640px;"
       width="640">
    <tbody>
    <tr style="border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-spacing: 0px;">
        <td style="border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-spacing: 0px; background-color: #FFE9E9;"
            bgcolor="#FFE9E9">
            <!--[if mso | IE]>
            <table cellpadding="0" cellspacing="0" border="0" align="center" style="width:100%" role="presentation" width="640">
                <tr>
                    <td style="line-height:0;font-size:0;-mso-line-height-rule:exactly"><![endif]-->
            <div class="bwfbe-block-section-outer-container"
                 style="margin: 0 auto; width: 640px; background-color: #FFE9E9;">
                <table cellpadding="0" cellspacing="0" border="0" align="center" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-spacing: 0px; line-height: normal; background-color: #FFE9E9; width: 100%; border-collapse: separate;" role="presentation" width="100%" class="bwfbe-block-section-inner-container" bgcolor="#FFE9E9"><tbody><tr style="border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-spacing: 0px;"><td style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-spacing: 0px; font-size: 0px; border-collapse: separate; padding: 36px; mso-padding-alt: 36px;"><!--[if mso | IE]><table cellpadding="0" cellspacing="0" border="0" style="width:100%;border-collapse:separate" role="presentation"><tbody><tr><![endif]--><!--[if mso | IE]><td style="width: 568px;vertical-align: top;" valign="top"><![endif]--><div class="bwf-email-inner-column-wrapper bwf-email-inner-column-wrapper-f21f8a5" style="font-size: 0px; border-collapse: separate; display: table-cell; vertical-align: top; mso-border-alt: none; width: 568px;"><table cellpadding="0" cellspacing="0" border="0" style="border-spacing: 0px; border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;" role="presentation" class="bwf-email-inner-column bwf-email-inner-column-f21f8a5" width="100%"><tbody><tr style="border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-spacing: 0px;"><td class="bwf-email-text bwf-email-text-b31192d" style="border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-spacing: 0px; padding: 0px 0px 8px 0px; word-break: break-word;"><div class="bwf-block-text-container" style="font-family: arial,helvetica,sans-serif; line-height: 1.5; font-size: 16px; text-align: center; font-size: 14px; font-family: arial,helvetica,sans-serif; line-height: 1.5; color: #353030;"><p class="bwf-block-text-inner-container" style="margin: 0; mso-line-height-alt: 150%; word-break: break-word; font-size: 14px; font-family: arial,helvetica,sans-serif; line-height: 1.5;"><span style="mso-line-height-alt: 150%; background-color: rgba(0, 0, 0, 0); color: #000000;" class="has-inline-color"><strong><span style="mso-line-height-alt: 150%; font-size: 16px;" class="has-font-size"><?php esc_html_e('Expired On:', 'Funnelkit'); ?> <?php echo esc_html($date); ?></span></strong></span></p></div></td></tr>

                                    <tr style="border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-spacing: 0px;"><td class="bwf-email-text bwf-email-text-11830a7" style="border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-spacing: 0px; padding: 0px 0px 8px 0px; word-break: break-word;"><div class="bwf-block-text-container" style="font-family: arial,helvetica,sans-serif; line-height: 1.5; font-size: 16px; text-align: center; font-size: 14px; font-family: arial,helvetica,sans-serif; line-height: 1.5; color: #353030;"><p class="bwf-block-text-inner-container" style="margin: 0; mso-line-height-alt: 150%; word-break: break-word; font-size: 14px; font-family: arial,helvetica,sans-serif; line-height: 1.5;"><span style="mso-line-height-alt: 150%; background-color: rgba(0, 0, 0, 0); color: #000000;" class="has-inline-color"><span style="mso-line-height-alt: 150%; font-size: 36px;" class="has-font-size"><strong><?php echo esc_html( $title ); ?></strong></span></span></p></div></td></tr>

                                    <tr style="border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-spacing: 0px;"><td class="bwf-email-text bwf-email-text-8520954" style="border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-spacing: 0px; padding: 0px 0px 8px 0px; word-break: break-word;"><div class="bwf-block-text-container" style="font-family: arial,helvetica,sans-serif; line-height: 1.5; font-size: 16px; text-align: center; font-size: 14px; font-family: arial,helvetica,sans-serif; line-height: 1.5; color: #353030;"><p class="bwf-block-text-inner-container" style="margin: 0; mso-line-height-alt: 150%; word-break: break-word; font-size: 14px; font-family: arial,helvetica,sans-serif; line-height: 1.5;"><span style="mso-line-height-alt: 150%; background-color: rgba(0, 0, 0, 0); color: #000000;" class="has-inline-color"><span style="mso-line-height-alt: 150%; font-size: 16px;" class="has-font-size"><?php echo esc_html( $subtitle ); ?></span></span></p></div></td></tr>

                                    <tr style="border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-spacing: 0px;"><td class="bwfbe-block-btn bwfbe-block-btn-f41b40e" align="center" style="border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-spacing: 0px; padding: 28px 16px 0px 16px; mso-padding-alt: 28px 16px 0px 16px;"><!--[if mso | IE]><span style="margin-left:16px"><![endif]--><table cellpadding="0" cellspacing="0" border="0" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-spacing: 0px; width: auto; border-collapse: separate;" role="presentation" class="bwfbe-block-btn-container"><tbody><tr style="border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-spacing: 0px;"><td class="bwfbe-btn-text-wrap" style="border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-spacing: 0px; font-size: 16px; cursor: auto; border-style: none; background-color: #E15334; font-size: 16px; border-radius: 8px 8px 8px 8px; mso-padding-alt: 10px 20px; mso-padding-alt: 10px 24px 10px 24px; text-align: center; line-height: 1.5;" bgcolor="#E15334" align="center"><a href="<?php echo esc_url( $button_url ); ?>" target="_blank" class="bwfbe-block-btn-content" style="line-height: 1.5; text-decoration: none; padding: 10px 20px; padding: 10px 24px 10px 24px; mso-padding-alt: 0; background-color: #E15334; font-size: 16px; font-family: arial,helvetica,sans-serif; display: inline-block; text-decoration: none; text-transform: none; color: #ffffff; border-radius: 8px 8px 8px 8px;"><strong><?php echo esc_html( $button_text ); ?></strong></a></td></tr></tbody></table><!--[if mso | IE]></span><![endif]--></td></tr></tbody></table></div><!--[if mso | IE]></td><![endif]--><!--[if mso | IE]></tr></tbody></table><![endif]--></td></tr></tbody></table>
            </div>
            <!--[if mso | IE]></td></tr></table><![endif]-->
        </td>
    </tr>
    </tbody>
</table>