<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit0df01a0d06af458d4ba3028d061d5119
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('BWFAN\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \BWFAN\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        // Platform check removed for optimization

        spl_autoload_register(array('ComposerAutoloaderInit0df01a0d06af458d4ba3028d061d5119', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \BWFAN\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit0df01a0d06af458d4ba3028d061d5119', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\BWFAN\Composer\Autoload\ComposerStaticInit0df01a0d06af458d4ba3028d061d5119::getInitializer($loader));

        $loader->register(true);

        return $loader;
    }
}
