<?php

// autoload_static.php @generated by Composer

namespace BWFAN\Composer\Autoload;

class ComposerStaticInit0df01a0d06af458d4ba3028d061d5119
{
    public static $prefixLengthsPsr4 = array (
        'B' => 
        array (
            'BWFAN\\Symfony\\Component\\CssSelector\\' => 35,
            'BWFAN\\Sabberworm\\CSS\\' => 20,
            'BWFAN\\Pelago\\Emogrifier\\' => 23,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'BWFAN\\Symfony\\Component\\CssSelector\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/css-selector',
        ),
        'BWFAN\\Sabberworm\\CSS\\' => 
        array (
            0 => __DIR__ . '/..' . '/sabberworm/php-css-parser/src',
        ),
        'BWFAN\\Pelago\\Emogrifier\\' => 
        array (
            0 => __DIR__ . '/..' . '/pelago/emogrifier/src',
        ),
    );

    public static $classMap = array (
        'BWFAN\\Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit0df01a0d06af458d4ba3028d061d5119::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit0df01a0d06af458d4ba3028d061d5119::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit0df01a0d06af458d4ba3028d061d5119::$classMap;

        }, null, ClassLoader::class);
    }
}
