<?php
// generated by Poedit from woocommerce-multiple-customer-addresses-it_IT.po, do not edit directly
return ['domain'=>NULL,'plural-forms'=>'nplurals=2; plural=(n != 1);','language'=>'it_IT','pot-creation-date'=>'2025-11-06 13:03+0100','po-revision-date'=>'2025-11-06 13:03+0100','translation-revision-date'=>'2025-11-06 13:03+0100','project-id-version'=>'WooCommerce Multiple Customer Addresses','x-generator'=>'Poedit 3.8','messages'=>[]];
